### ISSUE TITLE
More Assertions

### ISSUE THREAD

**Issue by nvzqz** [nvzqz/static-assertions-rs#2]
Discussion of other possible static assertions should occur here.

**Comment by skade** [comment]
Asserting Sync and Sendness: http://yakshav.es/asserting-static-properties/

Also, I'm still searching for a way to statically assert that a trait is object-safe.

**Comment by nvzqz** [comment]
@skade Just added [`assert_obj_safe`](https://github.com/nvzqz/static-assertions-rs/commit/047852274df04d2eff6e5361e13787ab99cbd57e) 👍

**Comment by nvzqz** [comment]
Here's a sample definition of a macro that would assert certain traits are implemented.

```rust
macro_rules! assert_impl {
    ($x:ty, $($xs:ty),+) => {
        $({
            fn _gen<T: ?Sized + $xs>() {}
            _gen::<$x>();
        })+
    };
    ($label:ident; $($xs:ty),+) => {
        #[allow(dead_code, non_snake_case)]
        fn $label() { assert_impl!($($xs),+); }
    };
}
```

However, when trying to use it, I get this error:

```
error: expected one of `(`, `,`, `=`, `>`, `?`, `for`, lifetime, or path, found `Sync`
   --> src/lib.rs:330:33
    |
330 |             fn _gen<T: ?Sized + $xs>() {}
    |                                -^^^ unexpected token
    |                                |
    |                                expected one of 8 possible tokens here
...
340 | assert_impl!(byte; u8, Sync);
    | ----------------------------- in this macro invocation
```

**Comment by nvzqz** [comment]
@skade Added [`assert_impl`](https://docs.rs/static_assertions/0.2.2/static_assertions/#assert-trait-impl) 🎉

**Comment by iliekturtles** [comment]
Would be cool to see an assertion that traits are *not* implemented: `assert_not_impl`.

**Comment by nvzqz** [comment]
There was some form of doing this that @kennytm recommend me. I don't exactly remember what it was.

**Comment by matthiasbeyer** [comment]
I would love to have something like

```
assert_str_startswith!(str, "and")
```

Usecase is a CLI-builder-pattern subcrate I am trying to build for [imag](https://github.com/matthiasbeyer/imag).

**Comment by nvzqz** [comment]
@matthiasbeyer This would likely have to be implemented as a procedural macro. In that case, both parameters would have to be string literals. I'm curious if this could be done via `const fn` in combination with `const_assert!`. 🤔

**Comment by robinkrahl** [comment]
Could you add a macro that asserts that an enum variant exists?

**Comment by nvzqz** [comment]
@jendrikw I finally decided to close #9 with 1f470d2a0d6197214a748481265625e6e678ec62.

It produces a rather nice error message:
```
error[E0308]: mismatched types
  --> tests/eq_ty.rs:12:5
   |
12 |     assert_eq_type!(byte; super::X, u8, usize, (super::X));
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u8, found usize
```

**Comment by ony** [comment]
How about `assert_ge_size!(u16, u8)` based on [`union`](https://doc.rust-lang.org/reference/items/unions.html) and `assert_eq_size!`?

Could be used in implementation of inlined polymorphic type that can handle any value as long as it fits into reserved storage.

**Comment by DrSensor** [comment]
Hi, I've struct and trait that require lifetime. My first though about using `assert_impl_all` is I need to specify the lifetime in precise manner:
```rust
assert_impl_all!(require;
	Transition<'t>,
	SemanticAnalyze<'t>,
	From<TokenPair<'t>>,
);
```
However, seems that's not supported. Rather I found traits need to be `'static` lifetime:
```rust
assert_impl_all!(require;
	Transition,
	SemanticAnalyze<'static>,
	From<TokenPair<'static>>,
);
```
I think this should be anonymous `'_` lifetime rather than `'static` lifetime 🤔

Ah yes, `#![feature(underscore_const_names)]` now has been stabilized 😁
<https://blog.rust-lang.org/2019/08/15/Rust-1.37.0.html#using-unnamed-const-items-for-macros>

**Comment by LucioFranco** [comment]
@nvzqz is there an issue for asserting `Unpin` and `!Unpin`? I know we talked about this at rustconf :)

**Comment by nvzqz** [comment]
@DrSensor the 1.0 beta is coming out soon. I'm dealing with life stuff which is why it hasn't come out yet. I tried getting around to it when 1.37 came out but I've had other priorities. Thanks for your patience!

@LucioFranco if you'd like to do the leg work to assert that the type of an expression implements given traits, please make a PR! To learn how to go about what we discussed, check out how `assert_eq_size_val!` and `assert_{not,}_impl_{any,all}!` are implemented. I'd be happy with doing it myself but this is a good opportunity to make a contribution I can mentor you on. 😄

**Comment by dtolnay** [comment]
I am interested for a static assertion that some trait bound currently in scope is statically impossible.

Example:

```rust
#![feature(trivial_bounds)]

macro_rules! void {
    ($($tt:tt)*) => {
        unreachable!() // FIXME
    };
}

trait Trait {
    fn f() where Self: Sized;
}

impl Trait for str {
    fn f() where str: Sized {
        void!(str: Sized); // evaluate to !
    }
}
```

This assertion should require that *both* `str: Sized` is currently in scope (e.g. in the example `let _s: str;` does compile, where ordinarily it would not) *and* `str: Sized` is statically unsatisfiable.

**Comment by Nadrieril** [comment]
@dtolnay: here is a sad version of what you ask:
```rust
macro_rules! void {
    ($ty:ty: $tr:path) => {{
        struct True;
        struct False;
        trait DoesImpl<M> {
            fn marker() {}
        }
        impl<T: ?Sized> DoesImpl<False> for T {}
        impl<T: ?Sized + $tr> DoesImpl<True> for T {}

        const _: () = {
            // Fails if `$ty: $tr` is in scope globally, because then it can't infer `M`
            let _ = <$ty as DoesImpl<_>>::marker;
        };
        // Fails if `$ty: $tr` is not in scope locally
        let _ = <$ty as DoesImpl<True>>::marker;

        unreachable!()
    }};
}
```

It will only typecheck in the case where the type does not implement the trait, but the bound `$ty: $tr` is in scope anyways.
I find this solution disappointing however: I'd love to be able to exploit the contradiction `str: Sized + !Sized` to construct a term of type `!`...

**Comment by dtolnay** [comment]
That looks fine to me. Is it something that would be a good fit for this crate?

**Comment by sunshowers** [comment]
It would be fantastic to have static assertions added for lifetime parameter covariance/contravariance/invariance, since changing it in a public API can be a semver breakage.

**Comment by Kixunil** [comment]
Is less than/greater than possible? More specifically, I'd be interested in `$len <= u8::max_value()`. Ideally for `u16` and larger too (so exhaustive 256 trait impls should not be used) but limiting it to `u8` is already useful. Bonus points if it works in Rust 1.41.1.

**Comment by konsumlamm** [comment]
@Kixunil isn't that already possible with `const_assert!(len <= u8::MAX)` (as long as `len` is `const`)? Apart from that, I'm not sure how something is ever going to be bigger than the maximum value of that type...

**Comment by Kixunil** [comment]
@konsumlamm frankly, I don't remember what I wanted to use it for but I believe `$len` in a macro was not of type `u8`.

**Comment by HTGAzureX1212** [comment]
Hi, would an extension for lifetimes in the assertions be useful? I ran across an issue with traits that require lifetime parameters and have to manually write the assertion based on the expansion that the `assert_*` macros do.

**Comment by newpavlov** [comment]
In my code I have several masks and flags with values computed using const computations. For example:
```rust
// For simplicity, concrete values used instead of const comp
const FOO_MASK: u8 = 0b0000_0111;
const BAR_FLAG: u8 = 0b0000_1000;
const ZOO_MASK: u8 = 0b1111_0000;
```
I want to assert at compile time that masks and flags fully cover all bits of an underlying type and do not intersect pairwise with each other. The first condition is easy and can be written as `const_assert_eq!(ZOO_MASK | BAR_FLAG | FOO_MASK, u8::MAX);`, but the second condition is more difficult. Naively writing `const_assert_eq!(ZOO_MASK & BAR_FLAG & FOO_MASK, 0);` does not work, so I have to explicitly write all pairwise combinations:
```rust
const_assert_eq!(ZOO_MASK | BAR_FLAG | FOO_MASK, u8::MAX);

const_assert_eq!(ZOO_MASK & BAR_FLAG, 0);
const_assert_eq!(ZOO_MASK & FOO_MASK, 0);
const_assert_eq!(BAR_FLAG & FOO_MASK, 0);
```
It becomes really annoying and error-prone with a bigger number of masks and fields packed into integer (imagine 10+ masks/flags in a 64 bit integer).

Right now I wrote a helper `const fn` which then gets `const_assert`-ed, but it would be nice to have such macro available out of box in this crate.
